#-------------------------------
# Site Settings
title: 金刻羽
description: Danto is a news and magazine Jekyll theme
logo: "/images/logo1.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo2.png"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "首页"
      url: "/"
    - title: "Latest"
      url: "/latest/"
    - title: "视音"
      url: "/videos/"
    - title: "金刻羽"
      url: "/about/"
    - title: "瞬间"
      url: "/elements/"
     
      
  




#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: 羽善观今
  hero_description: 


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "专栏"
    - tag: "专访"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


#-------------------------------



#-------------------------------
# Footer Settings
<center><a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备18026925号-4</a></center>

<center><div style="width:300px;margin:0 auto; padding:20px 0;">
     <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010402004000" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="https://qiniu.keyujin.cn/%E5%A4%87%E6%A1%88%E5%9B%BE%E6%A0%87.png" style="float:left;"/><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">浙公网安备 33010402004000号</p></a>
    </div>
</center>

# Social Links
social:
- {icon: "twitter", link: "https://twitter.com"}
- {icon: "facebook", link: "https://facebook.com"}
- {icon: "codepen", link: "https://codepen.io"}
- {icon: "pinterest", link: "https://pinterest.com"}
- {icon: "github", link: "https://github.com"}
- {icon: "youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------



#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
